ValueSet: VsIstatStato
Id: istat-stato
Title: "ISTAT - Stati"
Description: "ISTAT - Stati"
* ^experimental = false
//----------------------------------------
* $istat-stati#100 "Italia"
* $istat-stati#201 "Albania"
* $istat-stati#202 "Andorra"
* $istat-stati#203 "Austria"
* $istat-stati#206 "Belgio"
* $istat-stati#209 "Bulgaria"
* $istat-stati#212 "Danimarca"
* $istat-stati#214 "Finlandia"
* $istat-stati#215 "Francia"
* $istat-stati#216 "Germania"
* $istat-stati#219 "Regno Unito"
* $istat-stati#220 "Grecia"
* $istat-stati#221 "Irlanda"
* $istat-stati#223 "Islanda"
* $istat-stati#225 "Liechtenstein"
* $istat-stati#226 "Lussemburgo"
* $istat-stati#227 "Malta"
* $istat-stati#229 "Monaco"
* $istat-stati#231 "Norvegia"
* $istat-stati#232 "Paesi Bassi"
* $istat-stati#233 "Polonia"
* $istat-stati#234 "Portogallo"
* $istat-stati#235 "Romania"
* $istat-stati#236 "San Marino"
* $istat-stati#239 "Spagna"
* $istat-stati#240 "Svezia"
* $istat-stati#241 "Svizzera"
* $istat-stati#243 "Ucraina"
* $istat-stati#244 "Ungheria"
* $istat-stati#245 "Federazione russa"
* $istat-stati#246 "Stato della Città del Vaticano"
* $istat-stati#247 "Estonia"
* $istat-stati#248 "Lettonia"
* $istat-stati#249 "Lituania"
* $istat-stati#250 "Croazia"
* $istat-stati#251 "Slovenia"
* $istat-stati#252 "Bosnia-Erzegovina"
* $istat-stati#253 "Macedonia del Nord"
* $istat-stati#254 "Moldova"
* $istat-stati#255 "Slovacchia"
* $istat-stati#256 "Bielorussia"
* $istat-stati#257 "Repubblica ceca"
* $istat-stati#270 "Montenegro"
* $istat-stati#271 "Serbia"
* $istat-stati#272 "Kosovo"
* $istat-stati#301 "Afghanistan"
* $istat-stati#302 "Arabia Saudita"
* $istat-stati#304 "Bahrein"
* $istat-stati#305 "Bangladesh"
* $istat-stati#306 "Bhutan"
* $istat-stati#307 "Myanmar/Birmania"
* $istat-stati#309 "Brunei Darussalam"
* $istat-stati#310 "Cambogia"
* $istat-stati#311 "Sri Lanka"
* $istat-stati#314 "Cina"
* $istat-stati#315 "Cipro"
* $istat-stati#319 "Corea del Nord"
* $istat-stati#320 "Corea del Sud"
* $istat-stati#322 "Emirati Arabi Uniti"
* $istat-stati#323 "Filippine"
* $istat-stati#324 "Palestina"
* $istat-stati#326 "Giappone"
* $istat-stati#327 "Giordania"
* $istat-stati#330 "India"
* $istat-stati#331 "Indonesia"
* $istat-stati#332 "Iran"
* $istat-stati#333 "Iraq"
* $istat-stati#334 "Israele"
* $istat-stati#335 "Kuwait"
* $istat-stati#336 "Laos"
* $istat-stati#337 "Libano"
* $istat-stati#338 "Timor Leste"
* $istat-stati#339 "Maldive"
* $istat-stati#340 "Malaysia"
* $istat-stati#341 "Mongolia"
* $istat-stati#342 "Nepal"
* $istat-stati#343 "Oman"
* $istat-stati#344 "Pakistan"
* $istat-stati#345 "Qatar"
* $istat-stati#346 "Singapore"
* $istat-stati#348 "Siria"
* $istat-stati#349 "Thailandia"
* $istat-stati#351 "Turchia"
* $istat-stati#353 "Vietnam"
* $istat-stati#354 "Yemen"
* $istat-stati#356 "Kazakhstan"
* $istat-stati#357 "Uzbekistan"
* $istat-stati#358 "Armenia"
* $istat-stati#359 "Azerbaigian"
* $istat-stati#360 "Georgia"
* $istat-stati#361 "Kirghizistan"
* $istat-stati#362 "Tagikistan"
* $istat-stati#363 "Taiwan"
* $istat-stati#364 "Turkmenistan"
* $istat-stati#401 "Algeria"
* $istat-stati#402 "Angola"
* $istat-stati#404 "Costa d'Avorio"
* $istat-stati#406 "Benin"
* $istat-stati#408 "Botswana"
* $istat-stati#409 "Burkina Faso"
* $istat-stati#410 "Burundi"
* $istat-stati#411 "Camerun"
* $istat-stati#413 "Capo Verde"
* $istat-stati#414 "Repubblica Centrafricana"
* $istat-stati#415 "Ciad"
* $istat-stati#417 "Comore"
* $istat-stati#418 "Congo"
* $istat-stati#419 "Egitto"
* $istat-stati#420 "Etiopia"
* $istat-stati#421 "Gabon"
* $istat-stati#422 "Gambia"
* $istat-stati#423 "Ghana"
* $istat-stati#424 "Gibuti"
* $istat-stati#425 "Guinea"
* $istat-stati#426 "Guinea-Bissau"
* $istat-stati#427 "Guinea equatoriale"
* $istat-stati#428 "Kenya"
* $istat-stati#429 "Lesotho"
* $istat-stati#430 "Liberia"
* $istat-stati#431 "Libia"
* $istat-stati#432 "Madagascar"
* $istat-stati#434 "Malawi"
* $istat-stati#435 "Mali"
* $istat-stati#436 "Marocco"
* $istat-stati#437 "Mauritania"
* $istat-stati#438 "Maurizio"
* $istat-stati#440 "Mozambico"
* $istat-stati#441 "Namibia"
* $istat-stati#442 "Niger"
* $istat-stati#443 "Nigeria"
* $istat-stati#446 "Ruanda"
* $istat-stati#448 "Sao Tomé e Principe"
* $istat-stati#449 "Seychelles"
* $istat-stati#450 "Senegal"
* $istat-stati#451 "Sierra Leone"
* $istat-stati#453 "Somalia"
* $istat-stati#454 "Sudafrica"
* $istat-stati#455 "Sudan"
* $istat-stati#456 "Eswatini"
* $istat-stati#457 "Tanzania"
* $istat-stati#458 "Togo"
* $istat-stati#460 "Tunisia"
* $istat-stati#461 "Uganda"
* $istat-stati#463 "Repubblica Democratica del Congo"
* $istat-stati#464 "Zambia"
* $istat-stati#465 "Zimbabwe"
* $istat-stati#466 "Eritrea"
* $istat-stati#467 "Sud Sudan"
* $istat-stati#503 "Antigua e Barbuda"
* $istat-stati#505 "Bahamas"
* $istat-stati#506 "Barbados"
* $istat-stati#507 "Belize"
* $istat-stati#509 "Canada"
* $istat-stati#513 "Costa Rica"
* $istat-stati#514 "Cuba"
* $istat-stati#515 "Dominica"
* $istat-stati#516 "Repubblica Dominicana"
* $istat-stati#517 "El Salvador"
* $istat-stati#518 "Giamaica"
* $istat-stati#519 "Grenada"
* $istat-stati#523 "Guatemala"
* $istat-stati#524 "Haiti"
* $istat-stati#525 "Honduras"
* $istat-stati#527 "Messico"
* $istat-stati#529 "Nicaragua"
* $istat-stati#530 "Panama"
* $istat-stati#532 "Santa Lucia"
* $istat-stati#533 "Saint Vincent e Grenadine"
* $istat-stati#534 "Saint Kitts e Nevis"
* $istat-stati#536 "Stati Uniti d'America"
* $istat-stati#602 "Argentina"
* $istat-stati#604 "Bolivia"
* $istat-stati#605 "Brasile"
* $istat-stati#606 "Cile"
* $istat-stati#608 "Colombia"
* $istat-stati#609 "Ecuador"
* $istat-stati#612 "Guyana"
* $istat-stati#614 "Paraguay"
* $istat-stati#615 "Perù"
* $istat-stati#616 "Suriname"
* $istat-stati#617 "Trinidad e Tobago"
* $istat-stati#618 "Uruguay"
* $istat-stati#619 "Venezuela"
* $istat-stati#701 "Australia"
* $istat-stati#703 "Figi"
* $istat-stati#708 "Kiribati"
* $istat-stati#712 "Isole Marshall"
* $istat-stati#713 "Stati Federati di Micronesia"
* $istat-stati#715 "Nauru"
* $istat-stati#719 "Nuova Zelanda"
* $istat-stati#720 "Palau"
* $istat-stati#721 "Papua Nuova Guinea"
* $istat-stati#725 "Isole Salomone"
* $istat-stati#727 "Samoa"
* $istat-stati#730 "Tonga"
* $istat-stati#731 "Tuvalu"
* $istat-stati#732 "Vanuatu"
* $istat-stati#902 "Nuova Caledonia"
* $istat-stati#904 "Saint-Martin (FR)"
* $istat-stati#905 "Sahara occidentale"
* $istat-stati#906 "Saint-Barthélemy"
* $istat-stati#908 "Bermuda"
* $istat-stati#909 "Isole Cook (NZ)"
* $istat-stati#910 "Gibilterra"
* $istat-stati#911 "Isole Cayman"
* $istat-stati#917 "Anguilla"
* $istat-stati#920 "Polinesia francese"
* $istat-stati#924 "Isole Fær Øer"
* $istat-stati#925 "Jersey"
* $istat-stati#926 "Aruba"
* $istat-stati#928 "Sint Maarten (NL)"
* $istat-stati#934 "Groenlandia"
* $istat-stati#939 "Sark"
* $istat-stati#940 "Guernsey"
* $istat-stati#958 "Isole Falkland (Malvine)"
* $istat-stati#959 "Isola di Man"
* $istat-stati#964 "Montserrat"
* $istat-stati#966 "Curaçao"
* $istat-stati#972 "Isole Pitcairn"
* $istat-stati#980 "Saint Pierre e Miquelon"
* $istat-stati#983 "Sant'Elena"
* $istat-stati#988 "Terre australi e antartiche francesi"
* $istat-stati#992 "Isole Turks e Caicos"
* $istat-stati#994 "Isole Vergini britanniche"
* $istat-stati#997 "Wallis e Futuna"
* $istat-stati#998 "Altro/Non indicato/In corso di definizione"




ValueSet: VsIstatCittadinanza
Id: istat-cittadinanza
Title: "ISTAT - Cittadinanza"
Description: "ISTAT - Cittadinanza"
* ^experimental = false
//----------------------------------------
* $istat-stati#100 "Italia"
* $istat-stati#201 "Albania"
* $istat-stati#202 "Andorra"
* $istat-stati#203 "Austria"
* $istat-stati#206 "Belgio"
* $istat-stati#209 "Bulgaria"
* $istat-stati#212 "Danimarca"
* $istat-stati#214 "Finlandia"
* $istat-stati#215 "Francia"
* $istat-stati#216 "Germania"
* $istat-stati#219 "Regno Unito"
* $istat-stati#220 "Grecia"
* $istat-stati#221 "Irlanda"
* $istat-stati#223 "Islanda"
* $istat-stati#225 "Liechtenstein"
* $istat-stati#226 "Lussemburgo"
* $istat-stati#227 "Malta"
* $istat-stati#229 "Monaco"
* $istat-stati#231 "Norvegia"
* $istat-stati#232 "Paesi Bassi"
* $istat-stati#233 "Polonia"
* $istat-stati#234 "Portogallo"
* $istat-stati#235 "Romania"
* $istat-stati#236 "San Marino"
* $istat-stati#239 "Spagna"
* $istat-stati#240 "Svezia"
* $istat-stati#241 "Svizzera"
* $istat-stati#243 "Ucraina"
* $istat-stati#244 "Ungheria"
* $istat-stati#245 "Federazione russa"
* $istat-stati#246 "Stato della Città del Vaticano"
* $istat-stati#247 "Estonia"
* $istat-stati#248 "Lettonia"
* $istat-stati#249 "Lituania"
* $istat-stati#250 "Croazia"
* $istat-stati#251 "Slovenia"
* $istat-stati#252 "Bosnia-Erzegovina"
* $istat-stati#253 "Macedonia del Nord"
* $istat-stati#254 "Moldova"
* $istat-stati#255 "Slovacchia"
* $istat-stati#256 "Bielorussia"
* $istat-stati#257 "Repubblica ceca"
* $istat-stati#270 "Montenegro"
* $istat-stati#271 "Serbia"
* $istat-stati#272 "Kosovo"
* $istat-stati#301 "Afghanistan"
* $istat-stati#302 "Arabia Saudita"
* $istat-stati#304 "Bahrein"
* $istat-stati#305 "Bangladesh"
* $istat-stati#306 "Bhutan"
* $istat-stati#307 "Myanmar/Birmania"
* $istat-stati#309 "Brunei Darussalam"
* $istat-stati#310 "Cambogia"
* $istat-stati#311 "Sri Lanka"
* $istat-stati#314 "Cina"
* $istat-stati#315 "Cipro"
* $istat-stati#319 "Corea del Nord"
* $istat-stati#320 "Corea del Sud"
* $istat-stati#322 "Emirati Arabi Uniti"
* $istat-stati#323 "Filippine"
* $istat-stati#324 "Palestina"
* $istat-stati#326 "Giappone"
* $istat-stati#327 "Giordania"
* $istat-stati#330 "India"
* $istat-stati#331 "Indonesia"
* $istat-stati#332 "Iran"
* $istat-stati#333 "Iraq"
* $istat-stati#334 "Israele"
* $istat-stati#335 "Kuwait"
* $istat-stati#336 "Laos"
* $istat-stati#337 "Libano"
* $istat-stati#338 "Timor Leste"
* $istat-stati#339 "Maldive"
* $istat-stati#340 "Malaysia"
* $istat-stati#341 "Mongolia"
* $istat-stati#342 "Nepal"
* $istat-stati#343 "Oman"
* $istat-stati#344 "Pakistan"
* $istat-stati#345 "Qatar"
* $istat-stati#346 "Singapore"
* $istat-stati#348 "Siria"
* $istat-stati#349 "Thailandia"
* $istat-stati#351 "Turchia"
* $istat-stati#353 "Vietnam"
* $istat-stati#354 "Yemen"
* $istat-stati#356 "Kazakhstan"
* $istat-stati#357 "Uzbekistan"
* $istat-stati#358 "Armenia"
* $istat-stati#359 "Azerbaigian"
* $istat-stati#360 "Georgia"
* $istat-stati#361 "Kirghizistan"
* $istat-stati#362 "Tagikistan"
* $istat-stati#363 "Taiwan"
* $istat-stati#364 "Turkmenistan"
* $istat-stati#401 "Algeria"
* $istat-stati#402 "Angola"
* $istat-stati#404 "Costa d'Avorio"
* $istat-stati#406 "Benin"
* $istat-stati#408 "Botswana"
* $istat-stati#409 "Burkina Faso"
* $istat-stati#410 "Burundi"
* $istat-stati#411 "Camerun"
* $istat-stati#413 "Capo Verde"
* $istat-stati#414 "Repubblica Centrafricana"
* $istat-stati#415 "Ciad"
* $istat-stati#417 "Comore"
* $istat-stati#418 "Congo"
* $istat-stati#419 "Egitto"
* $istat-stati#420 "Etiopia"
* $istat-stati#421 "Gabon"
* $istat-stati#422 "Gambia"
* $istat-stati#423 "Ghana"
* $istat-stati#424 "Gibuti"
* $istat-stati#425 "Guinea"
* $istat-stati#426 "Guinea-Bissau"
* $istat-stati#427 "Guinea equatoriale"
* $istat-stati#428 "Kenya"
* $istat-stati#429 "Lesotho"
* $istat-stati#430 "Liberia"
* $istat-stati#431 "Libia"
* $istat-stati#432 "Madagascar"
* $istat-stati#434 "Malawi"
* $istat-stati#435 "Mali"
* $istat-stati#436 "Marocco"
* $istat-stati#437 "Mauritania"
* $istat-stati#438 "Maurizio"
* $istat-stati#440 "Mozambico"
* $istat-stati#441 "Namibia"
* $istat-stati#442 "Niger"
* $istat-stati#443 "Nigeria"
* $istat-stati#446 "Ruanda"
* $istat-stati#448 "Sao Tomé e Principe"
* $istat-stati#449 "Seychelles"
* $istat-stati#450 "Senegal"
* $istat-stati#451 "Sierra Leone"
* $istat-stati#453 "Somalia"
* $istat-stati#454 "Sudafrica"
* $istat-stati#455 "Sudan"
* $istat-stati#456 "Eswatini"
* $istat-stati#457 "Tanzania"
* $istat-stati#458 "Togo"
* $istat-stati#460 "Tunisia"
* $istat-stati#461 "Uganda"
* $istat-stati#463 "Repubblica Democratica del Congo"
* $istat-stati#464 "Zambia"
* $istat-stati#465 "Zimbabwe"
* $istat-stati#466 "Eritrea"
* $istat-stati#467 "Sud Sudan"
* $istat-stati#503 "Antigua e Barbuda"
* $istat-stati#505 "Bahamas"
* $istat-stati#506 "Barbados"
* $istat-stati#507 "Belize"
* $istat-stati#509 "Canada"
* $istat-stati#513 "Costa Rica"
* $istat-stati#514 "Cuba"
* $istat-stati#515 "Dominica"
* $istat-stati#516 "Repubblica Dominicana"
* $istat-stati#517 "El Salvador"
* $istat-stati#518 "Giamaica"
* $istat-stati#519 "Grenada"
* $istat-stati#523 "Guatemala"
* $istat-stati#524 "Haiti"
* $istat-stati#525 "Honduras"
* $istat-stati#527 "Messico"
* $istat-stati#529 "Nicaragua"
* $istat-stati#530 "Panama"
* $istat-stati#532 "Santa Lucia"
* $istat-stati#533 "Saint Vincent e Grenadine"
* $istat-stati#534 "Saint Kitts e Nevis"
* $istat-stati#536 "Stati Uniti d'America"
* $istat-stati#602 "Argentina"
* $istat-stati#604 "Bolivia"
* $istat-stati#605 "Brasile"
* $istat-stati#606 "Cile"
* $istat-stati#608 "Colombia"
* $istat-stati#609 "Ecuador"
* $istat-stati#612 "Guyana"
* $istat-stati#614 "Paraguay"
* $istat-stati#615 "Perù"
* $istat-stati#616 "Suriname"
* $istat-stati#617 "Trinidad e Tobago"
* $istat-stati#618 "Uruguay"
* $istat-stati#619 "Venezuela"
* $istat-stati#701 "Australia"
* $istat-stati#703 "Figi"
* $istat-stati#708 "Kiribati"
* $istat-stati#712 "Isole Marshall"
* $istat-stati#713 "Stati Federati di Micronesia"
* $istat-stati#715 "Nauru"
* $istat-stati#719 "Nuova Zelanda"
* $istat-stati#720 "Palau"
* $istat-stati#721 "Papua Nuova Guinea"
* $istat-stati#725 "Isole Salomone"
* $istat-stati#727 "Samoa"
* $istat-stati#730 "Tonga"
* $istat-stati#731 "Tuvalu"
* $istat-stati#732 "Vanuatu"
* $istat-stati#905 "Sahara occidentale"
* $istat-stati#926 "Aruba"
* $istat-stati#928 "Sint Maarten (NL)"
* $istat-stati#966 "Curaçao"
* $istat-stati#888 "Non cittadini riconosciuti"
* $istat-stati#998 "Altro/Non indicato/In corso di definizione"
* $istat-stati#999 "Apolide"



ValueSet: VsIstatComune
Id: istat-comune
Title: "ISTAT - Comuni"
Description: "ISTAT - Comuni più sconosciuto"
* ^experimental = false
//----------------------------------------
* include codes from system $cs-istat-comune  
* codes from system $cs-istat-comune
* $v3-NullFlavor#UNK "unknown"

ValueSet: VsIstatProvincia
Id: istat-provincia
Title: "ISTAT - Province"
Description: "ISTAT - Province più sconosciuto"
* ^experimental = false
//----------------------------------------
* $v3-NullFlavor#UNK "unknown"
* codes from system $cs-provincia


ValueSet: VsIstatLuogoNascita
Id: istat-luogoNascita
Title: "ISTAT - Comune/Stato di Nascita"
Description: "ISTAT - Comune/Stato di Nascita"
* ^experimental = false
//----------------------------------------
* include codes from valueset VsIstatStato
* include codes from valueset VsIstatComune